# Generated by Django 6.1.1 on 2026-09-29 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_type', models.CharField(choices=[('call', 'Phone Call'), ('interview', 'Interview'), ('email', 'Email'), ('text', 'Text / SMS'), ('site_visit', 'Site Visit'), ('other', 'Other')], max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'From Site'), ('outbound', 'To Site')], default='inbound', max_length=20)),
                ('site_name', models.CharField(help_text='Externship site name', max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_role', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=200)),
                ('notes', models.TextField(help_text='What was discussed / outcome')),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_communications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternshipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('searching', 'Searching for Site'), ('applied', 'Applications Submitted'), ('interviewing', 'Interviewing'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('placed', 'Placed / Started'), ('declined', 'Offer Declined'), ('on_hold', 'On Hold')], default='searching', max_length=30)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('site_location', models.CharField(blank=True, max_length=200)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='externship_status', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'externship statuses',
            },
        ),
    ]
